---
abstract: ~
author: []
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
distribution_type: script
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: makepp
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  MailingList: http://sourceforge.net/tracker/?group_id=43679&source=navbar
  bugtracker: http://sourceforge.net/tracker/?atid=437093&group_id=43679&func=browse
  homepage: http://makepp.sourceforge.net/
  license: http://dev.perl.org/licenses/
  repository: http://sourceforge.net/scm/?type=cvs&group_id=43679&source=navbar
version: 2.0.98.2cvs
